# secrets.toml
# cf. https://docs.streamlit.io/develop/concepts/connections/secrets-management
# can be deployed locally or in ./.streamlit/secrets.toml
# or in Streamlit Community Cloud

CONSUMER_KEY="my_api_key"
CONSUMER_SECRET="my_api_secret"
ACCESS_TOKEN="my_access_token"
ACCESS_TOKEN_SECRET="my_access_secret"
APP_PASSWORD="mYpassword"

[config]
textarea_font_size = 18